a = Analysis(
    ['galaxyos/kernel/mcp_server_entry.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('galaxyos', 'galaxyos'),
        ('skills', 'skills'),
    ],
    hiddenimports=[
        'galaxyos.kernel.mcp_server',
        'galaxyos.kernel.mcp_client',
        'galaxyos.kernel.liquid_memory_adapter',
        'galaxyos.kernel.dag_context_fusion',
        'galaxyos.kernel.memory_sync_bridge',
        'galaxyos.kernel.rccam_injector',
        'galaxyos.kernel.agent_core_bridge',
        'galaxyos.kernel.tokui_builder',
        'galaxyos.kernel.tokui_sse_streamer',
        'galaxyos.kernel.tokui_degradation',
        'galaxyos.kernel.skill_executor',
        'galaxyos.kernel.dual_runtime_manager',
        'galaxyos.kernel.llm_router_proxy',
        'galaxyos.shared.constants',
        'galaxyos.shared.paths',
        'galaxyos.shared.audit',
        'galaxyos.shared.fusion_guard',
        'galaxyos.harness.agent',
        'galaxyos.harness.workspace',
        'fastmcp',
        'numpy',
        'scipy',
        'pydantic',
        'httpx',
        'aiohttp',
        'orjson',
        'openai',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['torch', 'transformers', 'faiss', 'hnswlib', 'onnxruntime', 'pandas', 'tkinter', 'matplotlib'],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='galaxyos-mcp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    name='galaxyos-mcp',
)