[mypy]
no_implicit_optional = False
allow_untyped_defs = True
allow_incomplete_defs = True
disable_error_code = var-annotated, assignment, arg-type, union-attr, attr-defined, operator, return-value, name-defined, no-redef, valid-type, misc, index, dict-item, call-overload, has-type, func-returns-value, list-item, return, call-arg