[mypy]
no_implicit_optional = False
allow_untyped_defs = True
allow_incomplete_defs = True
disable_error_code = var-annotated, assignment, arg-type, union-attr, attr-defined, operator, return-value, name-defined, no-redef, valid-type, misc, index, dict-item, call-overload, has-type, func-returns-value, list-item, return, call-arg, import-not-found, import-untyped

[mypy.onnxruntime]
ignore_missing_imports = True

[mypy.openjiuwen.*]
ignore_missing_imports = True

[mypy.psutil]
ignore_missing_imports = True

[mypy.pyperclip]
ignore_missing_imports = True

[mypy.yaml]
ignore_missing_imports = True

[mypy.jieba.*]
ignore_missing_imports = True

[mypy.sklearn.*]
ignore_missing_imports = True

[mypy.numba]
ignore_missing_imports = True

[mypy.mkl]
ignore_missing_imports = True

[mypy.pysqlite3]
ignore_missing_imports = True

[mypy.aiosqlite]
ignore_missing_imports = True

[mypy.apscheduler.*]
ignore_missing_imports = True

[mypy.sqlite_vec]
ignore_missing_imports = True
